### ISSUE TITLE
Sry, i stupid

### ISSUE THREAD

**Issue by AndrijCat** [TheSpeedX/TBomb#10]
Remove this shit, because i can't verify with ads

**Comment by AndrijCat** [comment]
Sorry, i stupid and don't see the button :)

**Comment by TheSpeedX** [comment]
2 Great Working International API died because of overload on TBomb. People Are Bombing again and again Without any restriction Due to which I Lost Some Great APIs

You need to get A Code from the displayed Link Before You Gonna Proceed...

But if you gonna bomb indian numbers you need to verify only once unless you over use it
