### ISSUE TITLE
WARNING VIRUS POSSIBLE

### ISSUE THREAD

**Issue by EVRICA** [TheSpeedX/TBomb#20]
AUTHOR TheSpeedX if your bomber.py doesn't contain any viruses why did you encrypted your bomber.py code so that I cannot read it? why we can't see open source? What does it mean "Please Wait While We Verify Tbomb"? what exactly do you verifying at this moment and why? If you do not give answer on ALL my questions I will be FORCED TO CONSIDER THE CODE HAS VIRUS

**Comment by TheSpeedX** [comment]
We have got sensitive info like apis etc which if left open sourced will be heavily misused

At the time of verify we see if tbomb is latest or not and if any files is tampered
As i saw some people just editing there name in bash script and selling this script


Because We Get Overloaded We Had To Put Link Shorteners

Before i had no verification And People sent over 1000 msgs with international api
And A Pretty Good API Was Banned

By The Way Its Just temporary 
We will be releasing Android App Soon
So there will be no link shortener
And this script will be open sourced


Please See the other issues here @EVRICA I think you might have got your answer by now
If not feel free to comment

**Comment by EVRICA** [comment]
To be honest I have expected a rude answer, but you don't...
Thank you

**Comment by darkestentropy** [comment]
See #22, #5.

**Comment by xmagickx** [comment]
@TheSpeedX you've done a good job doing the encryption on one way that the APIs won't be leaked. It's the only way to sustain it. Make the encryption stronger. But don't put something sensitive in the script... If you know what I mean...

**Comment by TheSpeedX** [comment]
@xmagickx I dont do much stuff at backend i handle all stuff at client side only so i needed to
But soon i will make this script public 
Thanks For your recommendations

**Comment by xmagickx** [comment]
@TheSpeedX I appreciate your work... Just a note... You may make the script public I recommend you not reveal the bombing APIs publicly.. May reveal the script code but obfuscate the APIs separately..
