### ISSUE TITLE
dis script is nothing lollllll just send 1 messages to indians he try abuse indians lollllllll

### ISSUE THREAD

**Issue by microsoftsector1** [TheSpeedX/TBomb#23]
dis script is nothing lollllll just send 1 messages to indians he try abuse indians lollllllll
with fake followers lolllll

**Comment by darkestentropy** [comment]
>he try abuse indians

Not sure about that, but if 'getting paid for using gplinks.in' is considered an 'abuse' - that's the case for sure.

> fake followers

That's right, he has fake followers for real. Check comment left by @scpketer at issue [#19](https://github.com/TheSpeedX/TBomb/issues/19#issuecomment-524159937)

**Comment by darkestentropy** [comment]
You shouldn't create account for posting issues, actually.

**Comment by TheSpeedX** [comment]
@microsoftsector1 You can think what you want 
But if u think its fake please dont use it

@darkestentropy I thought u actually got what i wanted to say

@darkestentropy you can see @microsoftsector1 made a new github acc to just post an issue here
And whats the case that other users did not do the same for me or for some one else

If you guys think its fake dont use it, i will be rather happy than false accusations

**Comment by scpketer** [comment]
I can't send you similar bot for quite a few reasons.

1. I don't have any.
2. I'm too lazy to search for them because I'm quite certain that there are none.
3. Even if I had one, I'd never gave you one. You would just bring up thousands of new ones.

> bot which can bypass github's captcha xD

You see, accounts may be created by human. GitHub does not check if they were registered from the same IP.
Put 'em all together and make them [fork *something*](https://github.com/TheSpeedX/TBomb/network/members)/[follow *someone*](https://github.com/TheSpeedX/followers) - and we get what we have now.

**Comment by TheSpeedX** [comment]
@scpketer 
Yeah u can see commit bots source ..
And it could be shortened to few lines in bash if customizations are ignored

And yeah if u really think i have enough time to make like 100s of accounts in github..
I think u are a bit high...

Or this might be the case that u are just jealous may be  ( No offense ) 

If u really think i will use bots go the stars and forks , why not i will use in my other repos as well

And as far as i know , You contacted to github support right regarding this thing..
So what was the result????

And if u try log in multiple accounts github actually ask verification codes

And gihub actually does have a token like stuff , if u login from different device it asks for verification codes

And as far as i know i dont see that those github accounts were made with fake mails

I think you know almost all mail provider do verify user

So can u now say that i just made 100 mails like without verification and used in github and only on a single repo and not on others

Please settle down and think for a while about the challenges


> You shouldn't create new account just for posting issues, actually.

See this is what @darkestentropy  said to @microsoftsector1 
So dont u think @scpketer that those accounts might be the same case or other like posting issue etc to others.....

**Comment by scpketer** [comment]
> So dont u think @scpketer that those accounts might be the same case or other like posting issue etc to others.....

I see that that guy who made a cracker is not fake if you mean that. I mean, maybe someone's behind this account, cause they seem to be quite experienced in Git, PGP signing and Python/Makefile.

> I think you know almost all mail provider do verify user

There are temporary e-mail providers, you know. Those do nothing to verify users, trust me.

> If u really think i will use bots go the stars and forks , why not i will use in my other repos as well

Because your other repositories are quite average for a GitHub user.

**Comment by TheSpeedX** [comment]
@scpketer  
As quoted by you 
> There are temporary e-mail providers, you know. Those do nothing to verify users, trust me.
Do those accounts even get verified in github?? You can surely check a guys email right ..
So please first check that and then say what mail service they use?

> I see that that guy who made a cracker is not fake if you mean that. I mean, maybe someone's behind this account, cause they seem to be quite experienced in Git, PGP signing and Python/Makefile (and yet they only have TBomb forked and bombcrack repo created.)

I was talking about @microsoftsector1 in here

> Because your other repositories are quite average for a GitHub user.
Really man, Please get a clear view of my other repos...
if you think this is the best thing i have ever made Then you are 100% wrong....


i still did not get all of my answers
> And as far as i know , You contacted to github support right regarding this thing..
> So what was the result????

**Comment by scpketer** [comment]
I've asked them to respond to every action they take. Sadly, they've told I'm not allowed to ask this. AFAICS, there are no changes at your repo and your profile, can't really blame these guys. But that action was an optional one, I'm not going to take this as an answer to the 'Is this guy boosting their repo?'.

**Comment by TheSpeedX** [comment]
What changes you wa

**Comment by scpketer** [comment]
Any noticeable ones.

**Comment by TheSpeedX** [comment]
@scpketer Can u please elaborate

**Comment by scpketer** [comment]
Ones like wiping out fake forkers and stargazers.

**Comment by TheSpeedX** [comment]
> I'm not going to take this as an answer to the 'Is this guy boosting their repo?'.

Can u elaborate it

**Comment by scpketer** [comment]
I gave you a damn list of fake users right in my first issues - what else do you need as proper research?

**Comment by TheSpeedX** [comment]
Can u check what mail service they use like  GMail , outlook etc @scpketer 

Because i dont see they are fake mails as accused by you

And if they are not fake mails then issue is solved...
Which implies they were not bots or fake accounts

That i use just to get hype

And even if those are fake...
What about the insights and unique clones i get each month 
They are always 4 digits....

So What you wanna say about this??

And please dont say that i clone it again and again as github show normal clones and unique clones differently

**Comment by scpketer** [comment]
GitHub's insights are non-public. I can't tell if clones are unique or not, besides, I don't even mind clones.

Wait, I actually mind those. Since you say you have

> always 4 digits...

(which is over one thousand of unique cloners) - there should be a lot of people who want to stay in touch or contribute.
But for some odd reason, your contributors count doesn't grow, but you say you get >1k new cloners every month. 

_[\*Beep-beep-beep\* - discrepancy detected]_

**Comment by TheSpeedX** [comment]
I dont control Stargazers @scpketer might be you did not use the bot please run it and increase my stars

And as you are saying that from august 25 it increased by just 11 i will like to say you that this is repo is over 6 months old ...(So count out the average) ...

> there should be a lot of people who want to stay in touch or contribute.

yes a lot of guys are in my mail and i have other contributors too 
Please see the readme ..

> But for some odd reason, your contributors count doesn't grow [1], but you say you get >1k new cloners every month.

As of This month i have 4k+ unique clones and 6k+ total clones i can attach a screenshot if u like 

> . Are Indians really not into open source stuff?
You also have not send me any PRs 
So consider yours case as theirs
