### ISSUE TITLE
Barley any calls are being made.

### ISSUE THREAD

**Issue by Lucifer472** [TheSpeedX/TBomb#248]
Tbomb is making like one call per session and from same number. It is completely useless in india and if you block that one number it's done. You won't get any calls from it. So please fix this.

**Comment by t0xic0der** [comment]
@Lucifer472 calling the tool useless first and then requesting a fix for it is quite contradictory and disrespectful to the folks maintaining the project. It is not the maintainers' and/or the contributors' fault that the APIs are over-utilized and exploited.

**Comment by Lucifer472** [comment]
> @Lucifer472 calling the tool useless first and then requesting a fix for it is quite contradictory and disrespectful to the folks maintaining the project. It is not the maintainers' and/or the contributors' fault that the APIs are over-utilized and exploited.

Look Brother,
If I make game that is unplayable than there is no point in making that game. So if you make a tool that is not working than there is no point in making the tool in first place and as for the problem in over utilized api developers should have consider this possibility from the start and should have prevented that. I am not insulting anyone here I am just telling the truth and as always truth hurts.

**Comment by t0xic0der** [comment]
> If I make game that is unplayable than there is no point in making that game.

Irrelevant. The incentive is satisfied by the monetary benefit acquired from such a venture while TBomb is a FOSS project which we contribute to voluntarily in free time without getting paid. It is easy to mark out issues but difficult to help solve them.

> So if you make a tool that is not working than there is no point in making the tool in first place.

The star count being over 1k, watch count being over 250 and fork count being nearly 800 makes it evident that the tool works perfectly fine for others. Generalizing your case for other folks does not help them or help you in anyway.

> as for the problem in over utilized api developers should have consider this possibility from the start and should have prevented that

We are not storing usage metrics and analytical data from the users to protect their privacy so we do not get to know how much utilization is made for a single API. Plus, the APIs are not maintained by us due to which we cannot guarantee their availability.

@0n1cOn3 @TheSpeedX Feel free to close this ticket. The discussion is not heading anywhere.
